language: java

jdk:
  - oraclejdk8
  
sudo: false

before_script:
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1024m -XX:MaxPermSize=192m'" > ~/.mavenrc

script:
  - mvn install -Ptomcat,h2,engine-integration -pl qa/integration-tests-engine -am -DskipTests -s settings/maven/nexus-settings.xml -B
