language: java

jdk:
  - oraclejdk8
  
sudo: false

before_script:
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1024m -XX:MaxPermSize=192m'" > ~/.mavenrc

script:
  - mvn install -U -Ptomcat,h2 -am -Dmaven.test.skip=true -s settings/maven/nexus-settings.xml -B
